### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by sjaustad** [jdanders/ksl-classifieds-notifier#1]
Tried running with Beautiful Soup 4.6.0, 4.0.1, and 4.1.3 on Python 3.6 and 2.7 and keep getting this error with KSL.py

>   File "C:\Users\a050895\Desktop\beautifulsoup4-4.6.0\_OLD\ksl.py", line 45
    yield from ex.map(self.__do_request, self.build_qs(query, **etc))
             ^
SyntaxError: invalid syntax

And when I run KSL_notify.psy it gets this error
> C:\Users\a050895\Desktop\beautifulsoup4-4.6.0\_OLD>.\ksl_notify.py` --email sjaustad@gmail.com --logfile TEST1 razer
  File "C:\Users\a050895\Desktop\beautifulsoup4-4.6.0\_OLD\ksl_notify.py", line 41
    file=sys.stderr)
        ^
SyntaxError: invalid syntax`

I call it with .\ksl_notify.py --email myemail@gmail.com --logfile TEST1 Computer
Am I not using it right or is there an issue here?

**Comment by jdanders** [comment]
For the first error, I'm not sure why it would have a problem with the syntax of that line. This code is not python2 compatible, so don't try Python 2.7. I would almost think your files have messed up white-space or something.

For the second error you pasted, it looks like you are running on Windows (based on the "C:\" in your prompt) and without cygwin or some other Linux environment set up, the `./ksl_notify.py` way of running the program won't work. Try `python ksl_notify.py --email myemail@gmail.com --logfile TEST1 Computer` instead.
