### ISSUE TITLE
Not finding any matches

### ISSUE THREAD

**Issue by dclause1** [jdanders/ksl-classifieds-notifier#2]
KSL must have changed the page structure, because this isn't finding any matches.

**Comment by jdanders** [comment]
Hmm, that explains why I haven't gotten any notifications in a while...

Looks like they've dramatically changed the class types of the "div"s at the very least. I'll have to take a look when I get some time...

**Comment by dclause1** [comment]
I tried to look at it, but I’m not very familiar with Python.  

I think everything we care about is in the “listing-item-info” DIVs, but I couldn’t get BeautifulSoup to find them.

**Comment by jdanders** [comment]
Well, that was a major change. KSL is now rendering the local HTML with client-side javascript, so the HTML you see in a browser doesn't match what the script sees from the raw request. I now have to parse out the JSON structure in the javascript and use values from that dictionary. It actually simplified the `find_elements` function quite a bit, but I'm afraid parsing javascript in python is going to be pretty fragile...
