### ISSUE TITLE
data type issue

### ISSUE THREAD

**Issue by trevorhere** [jdanders/ksl-classifieds-notifier#3]
`Traceback (most recent call last):
  File "./ksl_notify.py", line 255, in <module>
    main(vars(args))
  File "./ksl_notify.py", line 198, in main
    time.sleep(loop_delay)
TypeError: an integer is required (got type str)
`

got this error after entering the suggested search in the ReadMe. Not sure how to fix it so I just entered a default time in time.sleep function.

**Comment by jdanders** [comment]
Thanks, looks like I haven't really used that parameter! I changed the parameter type to an `int` and the problem went away. Fixed in commit 727086f8add994efc1b4c61fc8e5c5f15db285d6.
